// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7LHAwJUsSNLuHTIBblTCgWwSYRJk_McU',
    appId: '1:466561013206:web:aa12f7af5734b7f0484077',
    messagingSenderId: '466561013206',
    projectId: 'whitematrixmachinetest',
    authDomain: 'whitematrixmachinetest.firebaseapp.com',
    storageBucket: 'whitematrixmachinetest.appspot.com',
    measurementId: 'G-WMQ5647X2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPWQaMLddJ8EFm2EzB8tO9D3mABI4c10',
    appId: '1:466561013206:android:959c721cfa7003f6484077',
    messagingSenderId: '466561013206',
    projectId: 'whitematrixmachinetest',
    storageBucket: 'whitematrixmachinetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdGt1ff-aLSMSXUOwEjf4rPrODpAlxtg',
    appId: '1:466561013206:ios:667ec2287bc92485484077',
    messagingSenderId: '466561013206',
    projectId: 'whitematrixmachinetest',
    storageBucket: 'whitematrixmachinetest.appspot.com',
    iosBundleId: 'com.whitematrix.machinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmdGt1ff-aLSMSXUOwEjf4rPrODpAlxtg',
    appId: '1:466561013206:ios:e828922b925cbaca484077',
    messagingSenderId: '466561013206',
    projectId: 'whitematrixmachinetest',
    storageBucket: 'whitematrixmachinetest.appspot.com',
    iosBundleId: 'com.example.whiteMatrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7LHAwJUsSNLuHTIBblTCgWwSYRJk_McU',
    appId: '1:466561013206:web:0829e33f9f405d2d484077',
    messagingSenderId: '466561013206',
    projectId: 'whitematrixmachinetest',
    authDomain: 'whitematrixmachinetest.firebaseapp.com',
    storageBucket: 'whitematrixmachinetest.appspot.com',
    measurementId: 'G-0ZHMT9YBE0',
  );
}